# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  - .yarn/

before_script:
  - apt-get update -qq && apt-get install -qy libelf1 gcc build-essential pkg-config g++ gyp
  - rm -rf $HOME/.node-gyp

test_core:
  script:
   - yarn global add node-gyp node-pre-gyp node-inspector
   - yarn config set cache-folder .yarn
   - yarn 
   - yarn coverage

